### PR TITLE
Gdrive folder select

### PR DESCRIPTION
**Pull request by jkayani**
Re-opening the pull request I had earlier. I modified the UI code to be more user-friendly, though it's still slightly flawed. I like this approach much better than what I had before; it imitates the Google Drive Picker more closely.

### CODE REVIEW

**Comment by rojer** [comment]
sorry for the delay in review, finally got to it and i like what i see. pretty neat way of dealing with hierarchical folders, good job!

this is pretty much ok to merge, other than formatting: can you please make the new code match existing style? namely, tabs -> spaces, tab stop = 2 instead of 8.

**Comment by rojer** [comment]
oh, and please remove "folder select" from the html page, it's pretty obvious what the dropdown is.

**Comment by jkayani** [comment]
I committed the changes you prescribed above. Glad I could contribute to the extension (it's my first pull request and project I've ever used Github with). Thanks a lot!

**Comment by rojer** [comment]
ok Josh, this looks good, i'm merging it.
a few more style nits, but i'll fix them up myself.

thanks again for your work! this will go out with the next beta (once i finish some refactoring i've been doing around full page captures).

**Pull request merged**
